### PR TITLE
i think this saves a little bit of gas since you do one less mload

### PR DESCRIPTION
**Pull request by elee1766**
title:

its a bit less clear to read but its a little cheaper. basically instead of doing two mloads into x1 and x2, just read them like a hi-lo

its a pretty simple change i dont think it should break anything unless im misunderstanding the casts somewhere, tests passed at least.

and sorry for some reason my indenting has been weird but i think i fixed it

### CODE REVIEW

**Comment by elee1766** [comment]
completely unrelated but 
image
is there any reason that this is / 2 / pi instead of / TWO_PI 
bc otherwise /TWO_PI is much cheaper

**Comment by mds1** [comment]
Looks great, nice job! Two small comments before merging:
1. The `2 / PI` should be changed to `TWO_PI`, good catch
2. Could add some more comments just explaining the logic, since like you said it's less clear but also because I love comments 😛

**Comment by elee1766** [comment]
sure hold on

**Comment by elee1766** [comment]
sorry that took a bit of time

currently, the contract uses int32 in order to match up the 4 byte width of the lut, and i was using uint32 to do the same thing. 

i dont think the lut bitwidth will ever change but just in case, i changed it to use a uint256 and a mask initialized based on the entry_bytes variable

it costs the same amount so i think it makes more sense than the cast, and should be safe as long as entry_bytes is never over 15

**Comment by mds1** [comment]
This looks awesome, thanks so much! 🙌

Can you enable the "allow edits by maintainers option" on the PR? Just want to force push a rebase which updates the gas snapshots, squashes the commits, and adds some comments around the sine table size

**Comment by elee1766** [comment]
this?
Screenshot_20211102-140804_Chrome

**Comment by mds1** [comment]
Yep, thanks! You might have already had it enabled. It was rejecting when I tried `git push https://github.com/elee1766/solidity-trigonometry.git HEAD -f`, but it worked with `git push https://github.com/elee1766/solidity-trigonometry.git HEAD:main -f`

**Pull request merged**
